// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateAndSuppressIssueSuccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CreateAndSuppressIssueSuccess', async function() {
    await driver.get("http://localhost:4321/signIn")
    await driver.setRect(550, 618)
    await driver.findElement(By.name("email")).sendKeys("nicolas.duroc@etu.u-bordeaux.fr")
    await driver.findElement(By.name("password")).sendKeys("abcdefgh")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("testing")).click()
    await driver.findElement(By.linkText("Backlog")).click()
    await driver.findElement(By.linkText("Nouvelle issue")).click()
    await driver.findElement(By.id("idInput")).click()
    await driver.findElement(By.id("idInput")).sendKeys("id")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("id")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("priority")).sendKeys("1")
    await driver.findElement(By.id("priority")).click()
    await driver.findElement(By.id("priority")).sendKeys("2")
    await driver.findElement(By.id("priority")).click()
    await driver.findElement(By.id("difficulty")).sendKeys("1")
    await driver.findElement(By.id("difficulty")).click()
    await driver.findElement(By.id("difficulty")).sendKeys("2")
    await driver.findElement(By.id("difficulty")).click()
    {
      const element = await driver.findElement(By.id("difficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("difficulty")).sendKeys("3")
    await driver.findElement(By.id("difficulty")).click()
    await driver.findElement(By.id("difficulty")).sendKeys("2")
    await driver.findElement(By.id("difficulty")).click()
    await driver.findElement(By.id("difficulty")).sendKeys("1")
    await driver.findElement(By.id("difficulty")).click()
    {
      const element = await driver.findElement(By.id("difficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("difficulty")).sendKeys("2")
    await driver.findElement(By.id("difficulty")).click()
    await driver.findElement(By.id("difficulty")).sendKeys("3")
    await driver.findElement(By.id("difficulty")).click()
    {
      const element = await driver.findElement(By.id("difficulty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("priority")).sendKeys("1")
    await driver.findElement(By.id("priority")).click()
    await driver.findElement(By.id("priority")).sendKeys("0")
    await driver.findElement(By.id("priority")).click()
    {
      const element = await driver.findElement(By.id("priority"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("priority")).sendKeys("1")
    await driver.findElement(By.id("priority")).click()
    await driver.findElement(By.id("priority")).sendKeys("2")
    await driver.findElement(By.id("priority")).click()
    {
      const element = await driver.findElement(By.id("priority"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("priority")).sendKeys("3")
    await driver.findElement(By.id("priority")).click()
    await driver.findElement(By.id("description")).sendKeys("En tant que issue, Je Peux issue, Afin de issue")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-danger")).click()
  })
})
