// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CreateAndSuppressIssueSuccessTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createAndSuppressIssueSuccess() {
    driver.get("http://localhost:4321/signIn");
    driver.manage().window().setSize(new Dimension(550, 618));
    driver.findElement(By.name("email")).sendKeys("nicolas.duroc@etu.u-bordeaux.fr");
    driver.findElement(By.name("password")).sendKeys("abcdefgh");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("testing")).click();
    driver.findElement(By.linkText("Backlog")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("id");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("priority")).sendKeys("1");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("priority")).sendKeys("2");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("difficulty")).sendKeys("1");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("difficulty")).sendKeys("2");
    driver.findElement(By.id("difficulty")).click();
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("difficulty")).sendKeys("3");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("difficulty")).sendKeys("2");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("difficulty")).sendKeys("1");
    driver.findElement(By.id("difficulty")).click();
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("difficulty")).sendKeys("2");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("difficulty")).sendKeys("3");
    driver.findElement(By.id("difficulty")).click();
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("priority")).sendKeys("1");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("priority")).sendKeys("0");
    driver.findElement(By.id("priority")).click();
    {
      WebElement element = driver.findElement(By.id("priority"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("priority")).sendKeys("1");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("priority")).sendKeys("2");
    driver.findElement(By.id("priority")).click();
    {
      WebElement element = driver.findElement(By.id("priority"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("priority")).sendKeys("3");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("description")).sendKeys("En tant que issue, Je Peux issue, Afin de issue");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
  }
}
