// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CreateModifyAndSuppressMultipleIssuesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createModifyAndSuppressMultipleIssues() {
    driver.get("http://localhost:4321/signIn");
    driver.manage().window().setSize(new Dimension(550, 618));
    driver.findElement(By.name("email")).sendKeys("nicolas.duroc@etu.u-bordeaux.fr");
    driver.findElement(By.name("password")).sendKeys("abcdefgh");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("testing")).click();
    driver.findElement(By.linkText("Backlog")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id");
    driver.findElement(By.id("name")).sendKeys("name");
    driver.findElement(By.id("priority")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id1");
    driver.findElement(By.id("name")).sendKeys("name1");
    driver.findElement(By.id("priority")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id2");
    driver.findElement(By.id("name")).sendKeys("name");
    driver.findElement(By.id("priority")).sendKeys("3");
    driver.findElement(By.id("difficulty")).sendKeys("5");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("En tant que ..., Je Peux ..., Afin de test");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id3");
    driver.findElement(By.id("name")).sendKeys("name3");
    driver.findElement(By.id("description")).sendKeys("En tant que test, Je Peux test, Afin de TEST");
    driver.findElement(By.cssSelector(".form-group:nth-child(4)")).click();
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("priority")).sendKeys("1");
    driver.findElement(By.id("difficulty")).sendKeys("2");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id4");
    driver.findElement(By.id("name")).sendKeys("name5");
    driver.findElement(By.id("priority")).sendKeys("9");
    driver.findElement(By.id("difficulty")).sendKeys("7");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id5");
    driver.findElement(By.id("name")).sendKeys("name9");
    driver.findElement(By.id("priority")).sendKeys("7");
    driver.findElement(By.id("difficulty")).sendKeys("6");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".media:nth-child(5) > .btn-primary")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("priority")).sendKeys("6");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("name")).sendKeys("name");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".media:nth-child(7) > .btn-primary")).click();
    driver.findElement(By.id("state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("state"));
      dropdown.findElement(By.xpath("//option[. = 'En cours']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("En tant que ..., Je Peux test, Afin de test\\n            ");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".media:nth-child(13) > .btn-primary")).click();
    driver.findElement(By.id("state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("state"));
      dropdown.findElement(By.xpath("//option[. = 'Terminée']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.id("difficulty")).sendKeys("7");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("priority")).sendKeys("8");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".media:nth-child(9) > .btn-primary")).click();
    driver.findElement(By.id("state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("state"));
      dropdown.findElement(By.xpath("//option[. = 'En cours']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.id("difficulty")).sendKeys("3");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("difficulty")).sendKeys("4");
    driver.findElement(By.id("difficulty")).click();
    {
      WebElement element = driver.findElement(By.id("difficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("difficulty")).sendKeys("5");
    driver.findElement(By.id("difficulty")).click();
    driver.findElement(By.id("priority")).sendKeys("2");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("priority")).sendKeys("3");
    driver.findElement(By.id("priority")).click();
    {
      WebElement element = driver.findElement(By.id("priority"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("priority")).sendKeys("4");
    driver.findElement(By.id("priority")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("name8");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".media:nth-child(3) .btn-danger")).click();
    driver.findElement(By.cssSelector(".media:nth-child(5) .btn-danger")).click();
    driver.findElement(By.cssSelector(".media:nth-child(9) .btn-danger")).click();
    driver.findElement(By.cssSelector(".media:nth-child(5) .btn-danger")).click();
    driver.findElement(By.cssSelector(".media:nth-child(5) .btn-danger")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
  }
}
