// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CreateAndSupressTaskWithUSlinkedSuccessTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createAndSupressTaskWithUSlinkedSuccess() {
    driver.get("http://localhost:4321/signIn");
    driver.manage().window().setSize(new Dimension(550, 618));
    driver.findElement(By.name("email")).sendKeys("nicolas.duroc@etu.u-bordeaux.fr");
    driver.findElement(By.name("password")).sendKeys("abcdefgh");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("testing")).click();
    driver.findElement(By.linkText("Backlog")).click();
    driver.findElement(By.linkText("Nouvelle issue")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id");
    driver.findElement(By.id("name")).sendKeys("name");
    driver.findElement(By.id("priority")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys("5");
    driver.findElement(By.id("difficulty")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Backlog")).click();
    driver.findElement(By.linkText("Tâches")).click();
    driver.findElement(By.linkText("Nouvelle tâche")).click();
    driver.findElement(By.id("idInput")).click();
    driver.findElement(By.id("idInput")).sendKeys("id");
    driver.findElement(By.id("description")).sendKeys("desc");
    driver.findElement(By.id("estimatedTime")).sendKeys("1h");
    driver.findElement(By.id("dependencies")).sendKeys("dep");
    driver.findElement(By.id("issueList")).click();
    {
      WebElement dropdown = driver.findElement(By.id("issueList"));
      dropdown.findElement(By.xpath("//option[. = 'id']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-group > button")).click();
    driver.findElement(By.id("assignedDeveloper")).click();
    driver.findElement(By.id("assignedDeveloper")).sendKeys("dev");
    driver.findElement(By.id("assignedDeveloper")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.linkText("Backlog")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.linkText("Tâches")).click();
  }
}
